chat_dir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from chat_rooms.views import GetRoomInfoView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('rooms/', include('chat_rooms.urls')),
    path('profile/', include('user_profile.urls')),
    path('api/rooms',GetRoomInfoView.as_view(),name='api'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat_rooms/urls.py
from django.urls import path
from . import views

app_name = 'chat_rooms'

urlpatterns = [
    path('', views.rooms, name='rooms'),
    path('<str:room_name>/', views.room, name='single_room'),


]

core/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


app_name ='core'
urlpatterns = [
    path('', views.frontpage, name='frontpage'),
    path('signup/', views.signup, name='signup'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name ='core/login.html'), name ='login'),
    path('', include('chat_rooms.urls'))

    ]

user_profile/urls.py
from django.urls import path
from django.contrib import admin
from .views import *


app_name = 'user_profile'

urlpatterns = [
    path('profile/<int:pk>/', profile_view, name='profile'),
    path('profile/<int:pk>/edit/', ProfileEdit.as_view(), name='profile_edit'),
    path('user_list/', GetUserList.as_view(), name = 'user_list')

    ]

chat_rooms/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Room(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    class Meta:
        app_label = 'chat_rooms'

    def __str__(self):
        return self.name



class Message(models.Model):
    rooom = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',),
        app_label = 'chat_rooms'

core/models.py
from django.db import models

# Create your models here.

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User



 # Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='media/', null=True, blank=True)

    def __str__(self):
        return str(self.user)

    # def save(self):
    #     super().save()
    #
    #     img = Image.open(self.avatar.path)
    #
    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields = ['username','password1', 'password2']

user_profile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

chat_rooms/views.py
from django.shortcuts import render
from .models import Room
from django.contrib.auth.decorators import login_required
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Room, Message,User
from .serializers import RoomSerializer, MessageSerializer
from django.views.generic import ListView, DetailView
# Create your views here.

@login_required
def rooms(request):
    rooms = Room.objects.all()

    return render(request,'rooms/room.html', {'rooms':rooms} )



@login_required
def room(request, room_name):

    return render(request, 'rooms/single_room.html', {'room_name': room_name})




class GetRoomInfoView(APIView):
    def get(self, request):

        queryset = Room.objects.all()
        serializer_for_queryset = RoomSerializer(
            instance=queryset,
            many=True
        )
        return Response(serializer_for_queryset.data)

core/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .forms import SignupForm
# Create your views here.
def frontpage(request):
    return render(request,'core/frontpage.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        print('Hello there')
        if form.is_valid():
            print('Form is valid')
            user = form.save()
            ## создать профиль!!!
            login(request, user)
            return redirect('core:frontpage')
        else:
            print('Form is not valid:', form.errors)
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {'form': form})

user_profile/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import Profile
from django.views.generic import DetailView, ListView
from django.shortcuts import get_object_or_404
from django.views.generic import UpdateView


@login_required
def profile_view(request, pk):

    profile = Profile.objects.get(user= request.user)

    return render(request, 'user_profile.html', {'profile': profile})


def profile_edit(request,pk):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Ваш профиль успешно обновлен.')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }

    return render(request, 'user_profile.html', context)


class ProfileEdit(UpdateView):
    template_name = 'profile_edit.html'
    model = Profile
    form_class = ProfileUpdateForm



class UserDetail(DetailView):
    model = Profile
    context_object_name = 'profile'


class GetUserList(ListView):
    model = Profile
    template_name = 'user_list.html'
    paginate_by = 5
    context_object_name = 'profiles'
    print('Oh hi')

chat_rooms/templates/rooms/room.html
{% extends "core/index.html" %}

{% block title %} Welcome {% endblock %}
{% block content %}
<div class="p-10 text-center">
        <h1 class=" text-3xl  lg;-10xl text-white">List of available chats</h1>
</div>

<div class='w-full flex flex-wrap items-center'>
    {% for room in rooms %}
    <div class ='w-full lg:w1/4 px-3 py-3 '>
        <div class="p-4 bg-white shadow rounded-xl text-center">
            <h3 class="mb-5 text-2xl font-semibold"> {{ room.name }}</h3>
            <a href="{% url 'chat_rooms:single_room' room.slug %}" class="px-5 py-3 block rounded-xl text-white bg-gray-300"> Join </a>
        </div>
    </div>

    {% endfor %}

</div>
{% endblock content %}

chat_rooms/templates/rooms/single_room.html
{% extends "core/index.html" %}

{% block title %} Welcome {% endblock %}
{% block content %}
<div class="p-10 text-center">
        <h1 class=" text-3xl  lg;-10xl text-white">{{ room.name }}</h1>
</div>

<div class='lg:w-2/4 mx-4 lg:mx-auto p-4 bg-white rounded-xl'>
        <div class=" example-message space-y-3" id ='example-message'>
                <div class="p-4 bg-gray-200">
                        <p class="font-semibold">Username </p>

                        <p> Sample message </p>
                </div>
        </div>
</div>
<div class="lg:w-2/4 mt-6 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
        <form method="post" action="." class="flex">
                {% csrf_token %}
                <input  type="text" name="content" class="flex-1 mr-3"  placeholder=" Input your message" id="message-input">
                <button class="px-5 py-3 rounded-xl text=white bg-blue-500 hover:bg-blue-700" id="message-submit"> Submit</button>

        </form>
</div>
 {{ room_name|json_script:"room-name" }}
`{{ request.user.username|json_script:"username"}}

    {% block scripts %}
     {# csrf_token #}
        <script>
            const roomName = JSON.parse(document.getElementById('room-name').textContent);
            const userName = JSON.parse(document.getElementById('username').textContent);
            console.log("Username",userName)
                const chatSocket = new WebSocket(
                'ws://'
                + window.location.host
                + '/ws/'
                + roomName
                + '/'

            );
            chatSocket.onopen = function() {
            console.log("Connection is established", roomName)
            }
            chatSocket.onmessage = function(e) {
                console.log(e)
                const data = JSON.parse(e.data);
                console.log("Data", data)
                if (data.message){
                    let html = "<div class='m-4 bg-gray-200'>"
                    html +=  "<p class='font-semibold'>"  + userName + "</p>"
                    html +=  "<p>"+ data.message + "</p> </div>";
                document.querySelector("#example-message").innerHTML += html;

                } else {
                alert("Message is empty");
                }
            };

            chatSocket.onclose = function(e) {
                console.error('Chat socket closed unexpectedly', e.error);
            };

            document.querySelector('#message-input').focus();
            document.querySelector('#message-input').onkeyup = function(e) {

                if (e.key === 'Enter') {  // enter, return
                    document.querySelector('#message-submit').click();
                }
            };
            const messageInputDom = document.querySelector('#message-input');
            console.log("messageInputDom", messageInputDom)
            document.querySelector('#message-submit').onclick = function(e) {
                e.preventDefault()
                const message = messageInputDom.value;
                console.log("MessageDom",message)
                chatSocket.send(JSON.stringify({
                    'message': message,
                    'username':userName,

                }));
                console.log("Message sent");
                messageInputDom.value = '';
            };
        </script>
    {% endblock %}
{% endblock content %}

core/templates/core/frontpage.html
{% extends "core/index.html" %}

{% block title %} Welcome {% endblock %}
{% block content %}
<div class="p-10 text-center">
        <h1 class=" text-3xl  lg;-10xl text-white">Welcome to MY_CHAT</h1>
    </div>
{% endblock content %}

core/templates/core/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name = 'viewport' content = 'width=device-width, initial-scale=1'>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title%} {% endblock %} </title>
</head>
<body class="bg-blue-300">
    <nav class="flex items-center justify-between px-5 py-6 bg-blue-700">
        <div>
            <a href="/" class="text-xl text-white ">MY_CHAT</a>
        </div>
        {% if request.user.is_authenticated %}

            <div class="flex items-center space-x-5">
                  <a href="{% url 'chat_rooms:rooms' %}" class='hover:text-gray-200'>Join chat</a>

                    <form method="post" action="{% url 'core:logout' %}">
                        {% csrf_token %}
                    <button type="submit">Logout</button>
                    </form>
            </div>
`           <div class="flex items-center space-x-5">
                <a href="{% url 'user_profile:profile' user.id %}" class ='hover:text-gray-200'>Profile</a>
            </div>
            <div class="flex items-center space-x-5">
                <a href="{% url 'user_profile:user_list' %}" class ='hover:text-gray-200'>User list<a>
            </div>
        {% else %}
            <div class="flex items-center space-x-5">
                <form method="post" action="{% url 'core:login' %}">
                        {% csrf_token %}
                    <button type="submit">Login</button>
                </form>

                <a href="signup/" class="px-4 py-5 rounded-xl text-white bg-blue-500">Signup</a>
            </div>
        {% endif %}
    </nav>

    {% block content %}
    {% endblock %}

</body>
</html>

core/templates/core/login.html
{% extends "core/index.html" %}

{% block title %} Login | {% endblock title %}
{% block content %}
    <div class="p-5 text-center">
        <h1 class="text-3xl lg:-6xl text-white">Signup please</h1>
    </div>
    <form method="post" action="." class="lg:w-1/4 px-4 mx-auto">
        {% csrf_token %}
        <div class="mb-5">
            <label class="text-white">Username</label>
            {{ form.username }}
        </div>

        <div class="mb-5">
            <label class="text-white">Password</label>
            {{ form.password }}
        </div>


        {% if form.errors %}
            <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                Ошибка
            </div>
        {% endif %}

        <button class="px-5 py-3 rounded-xl text-white bg-gray-600 hover:bg-gray-300">Submit</button>
    </form>
{% endblock content %}

core/templates/core/signup.html
{% extends "core/index.html" %}

{% block title %} Signup | {% endblock title %}
{% block content %}
    <div class="p-5 text-center">
            <h1 class=" text-3xl  lg;-6xl text-white">Signup please</h1>
    </div>
    <form method="post" action ='.' class="lg:w1/4 px-4 mx-auto">
            {% csrf_token %}
            <div class="mb-5">
               <label class='text-white'> Username </label>
                   <input type="text" name="username" class="w-full px-2 py-2 rounded-xl">
            </div>

            <div class="mb-5">
               <label class = 'text-white'> Password</label>
                   <input type="text" name="password1" class="w-full px-2 py-2 rounded-xl">
            </div>

            <div class="mb-5">
               <label class = 'text-white'> Repeat password </label>
                   <input type="text" name="password2" class="w-full px-2 py-2 rounded-xl">
            </div>

        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                    <p>{{error|escape}}</p>
                    </div>
                {% endfor %}
            {% endfor %}
        {% endif %}
    <button class="px-5 py-3 rounded-xl text-white bg-gray-600 hover:bg-gray-300">Submit</button>
    </form>
{% endblock content %}

user_profile/templates/profile_edit.html
{% extends "core/index.html" %}


{% block title %}Profile{% endblock %}

{% block content %}
<h2>Profile!!!</h2>
<div>
    <form method="POST" enctype="multipart/form-data">
      	{% csrf_token %}
		{{ form }}
      	<fieldset class="form-group">
          	<legend class="border-bottom mb-4">Your profile</legend>

      	</fieldset>
      	<div class="form-group">
          	<button class="btn btn-outline-info" type="submit">Edit</button>
      	</div>
  	</form>
</div>
{% endblock content %}

user_profile/templates/user_list.html
{% extends "core/index.html" %}

{% block title %} List of all users {% endblock %}
{% block content %}
{% for profile in profiles %}
    <div class ='w-full lg:w1/4 px-3 py-3 '>
        <div class="p-4 bg-white shadow rounded-xl text-center">
            <h3 class="mb-5 text-2xl font-semibold"> {{ profile.user.username }}</h3>
            <h3 class="mb-5 text-2xl font-semibold"> {{ profile.avatar }}</h3>


        </div>
    </div>
    {% endfor %}
{% endblock content %}

user_profile/templates/user_profile.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %} [3](https://studygyaan.com/django/how-to-use-bootstrap-forms-with-django-crispy-forms)[4](https://ordinarycoders.com/blog/article/render-forms-with-django-crispy-forms)

{% block title %}Profile{% endblock %}

{% block content %}
<h2>Profile</h2>

{% if profile.avatar %}
    <img class="w-10 h-10 p-1 rounded-full ring-2 ring-gray-300 dark:ring-gray-500" src="{{ profile.avatar.url }}"  alt="Avatar">
    <p class="flex items-left justify-between px-5 py-6">Username: {{ request.user.username }}</p>
{% else %}
    <p>Username: {{ request.user.username }}</p>
    <p>No avatar available.</p>

{% endif %}
<div>
	<div>
         <a href="{% url 'user_profile:profile_edit' request.user.pk %}" class='hover:text-gray-200'>Edit</a>
    </div>
</div>

{% endblock %}